ProjektPuszcze/Controllers/HomeController.cs
using System.Web.Mvc;

namespace ProjektPuszcze.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Dzialalnosc()
        {
            return View();
        }
        public ActionResult Kontakt()
        {
            return View();
        }
    }
}

ProjektPuszcze/Controllers/ViewSwitcherController.cs
using System.Web.Mvc;
using System.Web.WebPages;

namespace ProjektPuszcze.Controllers
{
    public class ViewSwitcherController : Controller
    {
        public RedirectResult SwitchView(bool mobile, string returnUrl) {
            if (Request.Browser.IsMobileDevice == mobile)
                HttpContext.ClearOverriddenBrowser();
            else
                HttpContext.SetOverriddenBrowser(mobile ? BrowserOverride.Mobile : BrowserOverride.Desktop);

            return Redirect(returnUrl);
        }
    }
}

ProjektPuszcze/Views/Home/Dzialalnosc.cshtml
@{
    ViewBag.Title = "Dzialalność - Projekt Puszcze";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container-fluid" style="padding: 0px">
    <div class="col-md-6" id="wyprawy1">
        <div class="page-header" id="wyprawyHeader"><h2>WYPRAWY</h2></div>
        <div class="col-md-6">
            <p>
                Puszcza Kampinoska -
                <a href="https://www.facebook.com/PieszoprzezwszystkiePuszczewPolsce/photos/?tab=album&album_id=1630959183841527">
                    zobacz opis
                </a>
            </p>
            <p>
                Puszcza Bydgoska -
                <a href="https://www.facebook.com/PieszoprzezwszystkiePuszczewPolsce/photos/?tab=album&album_id=1621342644803181">
                    zobacz opis
                </a>
            </p>
            <p>
                Puszcza Piska -
                <a href="https://www.facebook.com/PieszoprzezwszystkiePuszczewPolsce/photos/?tab=album&album_id=1621341191469993">
                    zobacz opis
                </a>
            </p>
            <p>
                Puszcza Goleniewska -
                <a href="https://www.facebook.com/PieszoprzezwszystkiePuszczewPolsce/photos/?tab=album&album_id=1547405055530274">
                    zobacz opis
                </a>
            </p>
            <p>
                Puszcza Rzepińska -
                <a href="https://www.facebook.com/PieszoprzezwszystkiePuszczewPolsce/photos/?tab=album&album_id=1526866640917449">
                    zobacz opis
                </a>
            </p>
        </div>
        <div class="col-md-6">
            <p>
                Puszcza Gorzowska -
                <a href="https://www.facebook.com/PieszoprzezwszystkiePuszczewPolsce/photos/?tab=album&album_id=1514969592107154">
                    zobacz opis
                </a>
            </p>
            <p>
                Puszcza Zielonka -
                <a href="https://www.facebook.com/PieszoprzezwszystkiePuszczewPolsce/photos/?tab=album&album_id=1472008953069885">
                    zobacz opis
                </a>
            </p>
            <p>
                Puszcza Białowieska -
                <a href="https://www.facebook.com/PieszoprzezwszystkiePuszczewPolsce/photos/?tab=album&album_id=1423492834588164">
                    zobacz opis
                </a>
            </p>
            <p>
                Puszcza Notecka -
                <a href="https://www.facebook.com/PieszoprzezwszystkiePuszczewPolsce/photos/?tab=album&album_id=1414422978828483">
                    zobacz opis
                </a>
            </p>
        </div>
    </div>
    <div class="col-md-6" id="wyprawy2">
        <div class="page-header" id="wyprawyHeader"><h2>SURVIVALE</h2></div>
        <div class="col-md-6">
            <p>
                Szkolenia survivalowe -
                <a href="https://www.facebook.com/PieszoprzezwszystkiePuszczewPolsce/photos/?tab=album&album_id=1414439065493541">
                    zobacz opis
                </a>
            </p>
        </div>
    </div>
    <div class="col-md-6" id="wyprawy2">
        <div class="page-header" id="wyprawyHeader"><h2>INNE</h2></div>
        <div class="col-md-6">
            <p>
                Samotny marsz wzdłuż rzeki Barycz -
                <a href="https://www.facebook.com/PieszoprzezwszystkiePuszczewPolsce/photos/?tab=album&album_id=1525863541017759">
                    zobacz opis
                </a>
            </p>
            <p>
                Nocny pierwszy marsz w Górze -
                <a href="https://www.facebook.com/PieszoprzezwszystkiePuszczewPolsce/photos/?tab=album&album_id=1417395398531241">
                    zobacz opis
                </a>
            </p>
            <p>
                Pierwszy etap przejścia wzdłuż Bałtyku -
                <a href="https://www.facebook.com/PieszoprzezwszystkiePuszczewPolsce/photos/?tab=album&album_id=1414423628828418">
                    zobacz opis
                </a>
            </p>
            <p>
                Drugi etap przejścia wzdłuż Bałtyku -
                <a href="https://www.facebook.com/PieszoprzezwszystkiePuszczewPolsce/photos/?tab=album&album_id=1414425112161603">
                    zobacz opis
                </a>
            </p>
            <p>
                Wypad w Bieszczady -
                <a href="https://www.facebook.com/PieszoprzezwszystkiePuszczewPolsce/photos/?tab=album&album_id=1414418908828890">
                    zobacz opis
                </a>
            </p>
        </div>
    </div>
    <div class="col-md-6" id="wyprawy1">
        <div class="page-header" id="wyprawyHeader"><h2>RECENZJE SPRZĘTU</h2></div>
        <div class="col-md-6">
            <p>
                Nóż TIM -
                <a href="https://www.facebook.com/PieszoprzezwszystkiePuszczewPolsce/photos/?tab=album&album_id=1438863703051077">
                    zobacz opis
                </a>
            </p>
            <p>
                Hamak Jungle US Army Armyworld -
                <a href="https://www.facebook.com/PieszoprzezwszystkiePuszczewPolsce/photos/?tab=album&album_id=1425948877675893">
                    zobacz opis
                </a>
            </p>
            <p>
                Baribal pokrowiec na nalgene -
                <a href="https://www.facebook.com/PieszoprzezwszystkiePuszczewPolsce/photos/?tab=album&album_id=1511511929119587">
                    zobacz opis
                </a>
            </p>
            <p>
                Kuchenka oraz pochwa z Kydexu  -
                <a href="https://www.facebook.com/PieszoprzezwszystkiePuszczewPolsce/photos/?tab=album&album_id=1543300262607420">
                    zobacz opis
                </a>
            </p>
        </div>
    </div>
</div>

<style>
    div#wyprawy1 {
        background: rgba(0,0,0,0.7);
        color: white;
        height: 30vh;
        padding: 0 2% 0 2%;
    }
    div#wyprawy2 {
        background: rgba(0,0,0,0.5);
        color: white;
        height: 30vh;
        padding: 0 2% 0 2%;
        margin-top: 0px;
    }
    div.container-fluid a{
        color: #ffd800;
    }
    #wyprawyHeader {
        margin: 2%;
    }
    p a {
        font-weight: bold;
    }
</style>

ProjektPuszcze/Views/Home/Dzialalnosc.mobile.cshtml
@{
    ViewBag.Title = "Projekt Puszcze - Działalność";
    Layout = "~/Views/Shared/_Layout.Mobile.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Dzialalnoscmobile</title>
</head>
<body>
    <ul data-role="listview" data-inset="true" data-divider-theme="a">
        <li data-role="list-divider">Wyprawy</li>
        <li>
            <a href="https://www.facebook.com/PieszoprzezwszystkiePuszczewPolsce/photos/?tab=album&album_id=1630959183841527">
                Puszcza Kampinoska
            </a>
        </li>
        <li>
            <a href="https://www.facebook.com/PieszoprzezwszystkiePuszczewPolsce/photos/?tab=album&album_id=1621342644803181">
                Puszcza Bydgoska
            </a>
        </li>
        <li>
            <a href="https://www.facebook.com/PieszoprzezwszystkiePuszczewPolsce/photos/?tab=album&album_id=1621341191469993">
                Puszcza Piska
            </a>
        </li>
        <li>
            <a href="https://www.facebook.com/PieszoprzezwszystkiePuszczewPolsce/photos/?tab=album&album_id=1547405055530274">
                Puszcza Goleniewska
            </a>
        </li>
        <li>
            <a href="https://www.facebook.com/PieszoprzezwszystkiePuszczewPolsce/photos/?tab=album&album_id=1526866640917449">
                Puszcza Rzepińska
            </a>
        </li>
        <li data-role="list-divider">Survivale</li>
        <li>
            <a href="https://www.facebook.com/PieszoprzezwszystkiePuszczewPolsce/photos/?tab=album&album_id=1414439065493541">
                Szkolenia survivalowe
            </a>
        </li>
        <li data-role="list-divider">Inne</li>
        <li>
            <a href="https://www.facebook.com/PieszoprzezwszystkiePuszczewPolsce/photos/?tab=album&album_id=1525863541017759">
                Samotny marsz wzdłuż rzeki Barycz
            </a>
        </li>
        <li>
            <a href="https://www.facebook.com/PieszoprzezwszystkiePuszczewPolsce/photos/?tab=album&album_id=1417395398531241">
                Nocny pierwszy marsz w Górze
            </a>
        </li>
        <li>
            <a href="https://www.facebook.com/PieszoprzezwszystkiePuszczewPolsce/photos/?tab=album&album_id=1414423628828418">
                Pierwszy etap przejścia wzdłuż Bałtyku
            </a>
        </li>
        <li>
            <a href="https://www.facebook.com/PieszoprzezwszystkiePuszczewPolsce/photos/?tab=album&album_id=1414425112161603">
                Drugi etap przejścia wzdłuż Bałtyku
            </a>
        </li>
        <li>
            <a href="https://www.facebook.com/PieszoprzezwszystkiePuszczewPolsce/photos/?tab=album&album_id=1414418908828890">
                Wypad w Bieszczady
            </a>
        </li>
        <li data-role="list-divider">Recenzje sprzętu</li>
        <li>
            <a href="https://www.facebook.com/PieszoprzezwszystkiePuszczewPolsce/photos/?tab=album&album_id=1438863703051077">
                Nóż TIM
            </a>
        </li>
        <li>
            <a href="https://www.facebook.com/PieszoprzezwszystkiePuszczewPolsce/photos/?tab=album&album_id=1425948877675893">
                Hamak Jungle US Army Armyworld
            </a>
        </li>
        <li>
            <a href="https://www.facebook.com/PieszoprzezwszystkiePuszczewPolsce/photos/?tab=album&album_id=1511511929119587">
                Baribal pokrowiec na nalgene
            </a>
        </li>
        <li>
            <a href="https://www.facebook.com/PieszoprzezwszystkiePuszczewPolsce/photos/?tab=album&album_id=1543300262607420">
                Kuchenka oraz pochwa z Kydexu
            </a>
        </li>
        <li data-role="list-divider">
            <a href="https://www.facebook.com/PieszoprzezwszystkiePuszczewPolsce/">Więcej na Facebooku</a>
        </li>
    </ul>
</body>
</html>

<style>
    ul li a {
        font-size: 12px !important;
    }
</style>

ProjektPuszcze/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Projekt Puszcze";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="text">
    <div class="container-fluid" style="color:white">
        <div class="page-header" style="margin:30px"><h2>O PROJEKCIE</h2></div>
        <p>
            W dzisiejszych czasach ciężko jest ludziom znaleźć miejsce dzięki, któremu choć na chwilę
            można odciąć się od hałasu, zgiełku miast i ciągłego pośpiechu. Las jest miejscem magicznym w
            którym każdy z nas może się zatrzymać, odetchnąć choć na chwilę. Las to przede wszystkim szum
            drzew, ptaków śpiew i cisza, która ukoi każdą duszę...<br />
        </p>
        <p>
            W Polsce jest wiele przepięknych kompleksów leśnych, które niestety zostały przez nas
            nieco zapomniane... Dlatego też powstał projekt „Piechur- pieszo przez wszystkie puszcze w
            Polsce”, którego celem jest poznanie i promocja dzikich terenów polskich puszczy. Celem
            niniejszego projektu jest również zachęcanie ludzi do aktywnego spędzania czasu, szczególnie na
            łonie natury.<br />
        </p>
        <p style="margin-bottom: 30px">
            Na terenie naszego kraju jest aż 25 puszczy, a najwięcej z nich znajdziemy na terenach
            Warmii i Mazur zwanymi Zielonymi Płucami.
        </p>
    </div>
</div>
<div class="container-fluid" style="background: rgba(128, 128, 128,0.7)">
    <h2 style="color: white; text-align: center;">POZNAJ UCZESTNIKÓW PROJEKTU !</h2>
</div>
    <div class="container">
        <div id="myCarousel" class="carousel slide" data-ride="carousel">
            <!-- Indicators -->
            <ol class="carousel-indicators">
                <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                <li data-target="#myCarousel" data-slide-to="1"></li>
                <li data-target="#myCarousel" data-slide-to="2"></li>
                <li data-target="#myCarousel" data-slide-to="3"></li>
            </ol>

            <!-- Wrapper for slides -->
            <div class="carousel-inner" role="listbox">

                <div class="item active">
                    <img class="img-responsive" alt="Seweryn Kubicki" src="@Url.Content("~/Content/serweryn.png")" />
                    <div class="carousel-caption" id="carousel-text">
                        <h3>Seweryn Kubicki - pomysłodawca projektu</h3>
                        <p>Wiek: 24</p>
                        <p>Pasja: przyroda, survival, wędkarstwo, fotografia, ultra maratony górskie.</p>
                        <p>Motto: Pamiętaj kim jesteś.</p>
                    </div>
                </div>

                <div class="item">
                    <img class="img-responsive" alt="Dariusz Mitręga" src="@Url.Content("~/Content/dariusz.png")" />
                    <div class="carousel-caption" id="carousel-text">
                        <h3>Dariusz Mitręga - właściciel firmy Survival Team</h3>
                        <p>Wiek: 50 lat</p>
                        <p>Pasja: survival, przyroda szeroko pojęta, góry-treking, morze-żagle, nurkowanie, podróże.</p>
                        <p>Motto: nie ma rzeczy nie możliwych, są tylko trudne decyzje.</p>
                    </div>
                </div>
                <div class="item">
                    <img class="img-responsive" alt="Konrad Busza" src="@Url.Content("~/Content/rafal3.jpg")" />
                    <div class="carousel-caption" id="carousel-text">
                        <h3>Konrad Busza</h3>
                    </div>
                </div>
                <div class="item">
                    <img class="img-responsive" alt="Rafał Bauer" src="@Url.Content("~/Content/konrad2.jpg")" />
                    <div class="carousel-caption" id="carousel-text">
                        <h3>Rafał Bauer</h3>
                    </div>
                </div>

            </div>
            <!-- Left and right controls -->
            <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
    </div>

<div class="container-fluid" id="sponsoring">
    <div class="col-md-2" id="sponsor">
        <a href="http://www.brubeck.pl"><img class="img-responsive" alt="Brubeck" src="@Url.Content("~/Content/Sponsors/brubeck.jpg")" /></a>
    </div>
    <div class="col-md-2" id="sponsor">
        <a href="http://www.emilitaria.pl"> <img class="img-responsive" alt="emilitaria.pl" src="@Url.Content("~/Content/Sponsors/emilitaria.png")" /></a>
    </div>
    <div class="col-md-4">
        <h1 style="text-align: center; color: grey; text-decoration: solid; vertical-align: central;"><b>SPONSORZY</b></h1>
    </div>
    <div class="col-md-2" id="sponsor">
        <a href="http://graff-team.com/pl/"> <img class="img-responsive" alt="Graff" src="@Url.Content("~/Content/Sponsors/graff.jpg")" /></a>
    </div>
    <div class="col-md-2" id="sponsor">
        <a href="http://www.fiskars.pl"><img class="img-responsive" alt="FISKARS" src="@Url.Content("~/Content/Sponsors/fiskars.png")" /></a>
    </div>
    <div class="col-md-2" id="sponsor">
        <a href="http://www.naturvival.pl"><img class="img-responsive" ALT="International outdoor federation"src="@Url.Content("~/Content/Sponsors/iof.jpg")" /></a>
    </div>
    <div class="col-md-2" id="sponsor">
        <img class="img-responsive" alt="JACH PROJEKT"src="@Url.Content("~/Content/Sponsors/jach.png")" />
    </div>
    <div class="col-md-2" id="sponsor">
        <a href="http://www.lesovik.eu"><img class="img-responsive" alt="LESOVIK" src="@Url.Content("~/Content/Sponsors/lesovik.png")" /></a>
    </div>
    <div class="col-md-2" id="sponsor">
        <a href="http://www.naostrzu.pl"><img class="img-responsive" alt="Na ostrzu" src="@Url.Content("~/Content/Sponsors/naostrzu.png")" /></a>
    </div>
    <div class="col-md-2" id="sponsor">
        <img class="img-responsive" alt="SPOŁEM" src="@Url.Content("~/Content/Sponsors/spolem.png")" />
    </div>
    <div class="col-md-2" id="sponsor">
        <a href="http://www.surgepolonia.pl"><img class="img-responsive" alt="SURGE" src="@Url.Content("~/Content/Sponsors/surge.png")" /></a>
    </div>
    <div class="col-md-2" id="sponsor">
        <a href="http://www.outdorzy.pl"><img class="img-responsive" alt="Outdoorzy" src="@Url.Content("~/Content/Sponsors/outdorzy.jpg")" /></a>
    </div>
    <div class="col-md-2" id="sponsor">
        <a href="http://www.tlim.net"><img class="img-responsive" alt="TLIM" src="@Url.Content("~/Content/Sponsors/tlim.jpg")" /></a>
    </div>
    <div class="col-md-2" id="sponsor">
        <a href="http://www.gora.com.pl/"><img class="img-responsive" alt="Gmina Góra" src="@Url.Content("~/Content/Sponsors/gora.png")" /></a>
    </div>
    <div class="col-md-2" id="sponsor">
        <a href="http://www.http://fogtbikes.pl/"><img class="img-responsive" alt="Fogt Bikes" src="@Url.Content("~/Content/Sponsors/fogt.png")" /></a>
    </div>
    <div class="col-md-2" id="sponsor">
        <a href="http://www.baribal.pl"><img class="img-responsive" alt="Baribal" src="@Url.Content("~/Content/Sponsors/baribal.png")" /></a>
    </div>
    <div class="col-md-2" id="sponsor">
        <a href="http://www.survivaltech.pl"><img class="img-responsive" alt="Survival Tech" src="@Url.Content("~/Content/Sponsors/surv.png")" /></a>
    </div>
</div>

ProjektPuszcze/Views/Home/Index.mobile.cshtml
@{
    ViewBag.Title = "Projekt Puszcze";
    Layout = "~/Views/Shared/_Layout.Mobile.cshtml";
}

<body>
    <a href="@Url.Action("Index", "Home")">
        <img class="img-responsive" style="width: 100%;" alt="PROJEKT PUSZCZE" src="@Url.Content("~/Content/header.jpg")" />
    </a>
    <div class="ui-corner-all custom-corners">
        <div class="ui-bar ui-bar-a">
            <h3>O projekcie</h3>
        </div>
        <div class="ui-body ui-body-a">
            <p>
                W Polsce jest wiele przepięknych kompleksów leśnych, które niestety zostały przez nas
                nieco zapomniane...
                Dlatego też powstał projekt
                <b>„Piechur - pieszo przez wszystkie puszcze w Polsce”</b>, którego celem jest poznanie i promocja dzikich terenów polskich puszczy. <br />
            </p>
            <p>
            Celem niniejszego projektu jest również zachęcanie ludzi do aktywnego spędzania czasu, szczególnie na
            łonie natury.
            </p>
        </div>
    </div>
    <div class="ui-corner-all custom-corners">
        <div class="ui-bar ui-bar-a">
            <h3>Uczestnicy projektu</h3>
        </div>
        <div class="ui-body ui-body-a" style="margin: 0; padding: 0">
            <ul data-role="listview" data-split-icon="gear" data-split-theme="a" data-inset="true" style="margin: 0">
                <li>
                    <img alt="Seweryn Kubicki" src="@Url.Content("~/Content/seweryn_icon.png")" />
                    <p>Seweryn Kubicki</p>
                    <p id="desc">Pomysłodawca projektu</p>
                </li>
                <li>
                    <img class="img-responsive" alt="Dariusz Mitręga" src="@Url.Content("~/Content/dariusz_icon.png")" />
                    <p>Dariusz Mitręga</p>
                    <p id="desc">Właściciel firmy Survival Team</p>
                </li>
                <li>
                    <img class="img-responsive" alt="Konrad Busza" src="@Url.Content("~/Content/rafal_icon.png")" />
                    <p>Konrad Busza</p>
                    <p id="desc">Uczestnik projektu</p>
                </li>
                <li>
                    <img class="img-responsive" alt="Rafał Bauer" src="@Url.Content("~/Content/konrad_icon.png")" />
                    <p>Rafał Bauer</p>
                    <p id="desc">Uczestnik projektu</p>
                </li>
            </ul>
        </div>
    </div>
</body>

<style>
    p {
        text-indent: 10%;
        font-size: 10px;
        text-align: justify;
    }
    img {
        width: 100%;
    }
    #desc {
        font-size: 10px;
    }
</style>

ProjektPuszcze/Views/Home/Kontakt.mobile.cshtml
@{
    ViewBag.Title = "Kontakt - Projekt Puszcze";
    Layout = "~/Views/Shared/_Layout.Mobile.cshtml";
}

<body>
    <ul data-role="listview">
        <li data-role="list-divider">Zapraszamy do kontaktu !</li>
    </ul>
    <div class="img">
        <a target="_blank" href="~/Content/kontakt.jpg">
            <img src="~/Content/kontakt.jpg" alt="Kontakt">
        </a>
        <div class="desc">
            <ul data-role="listview">
                <li>
                    <a style="font-size: 10px !important; text-align: center !important;" href="https://www.facebook.com/PieszoprzezwszystkiePuszczewPolsce/">
                        Facebook Fanpage
                    </a>
                </li>
                <li data-role="list-divider" style="font-size: 10px !important;">
                    E-mail: <b>email@email.com</b>
                </li>
            </ul>
        </div>
    </div>
</body>

<style>
    p {
        margin: auto;
    }
    div.img {
        margin: 0;  
        border: 1px solid #ccc;
        width: 90vw;
        height: 90vh;
    }
    div.img:hover {
        border: 1px solid #777;
    }

    div.img img {
        width: 100%;
        height: auto;
    }

    div.desc {
        text-align: center;
    }
    div ul li {
        text-align: center !important;
    }
</style>

ProjektPuszcze/Views/Shared/_Layout.Mobile.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>
    <meta name="viewport" content="width=device-width" />
    @Styles.Render("~/Content/Mobile/css", "~/Content/jquerymobile/css")
    @Scripts.Render("~/bundles/jquery", "~/bundles/jquerymobile")
    <script>
        $(document).ready(function () {
            $.mobile.ajaxEnabled = false;
        });
    </script>
    <link href="~/Content/Styles/Styles.css" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="http://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.css" />
    <script src="http://code.jquery.com/jquery-1.11.1.min.js"></script>
    <script src="http://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.js"></script>
</head>

<body>
    <div data-role="navbar">
        <ul>
            <li><a href="@Url.Action("Index", "Home")">O Projekcie</a></li>
            <li><a href="@Url.Action("Dzialalnosc", "Home")">Działalność</a></li>
            <li><a href="@Url.Action("Kontakt", "Home")">Kontakt</a></li>
        </ul>
    </div>
    <!-- /
         -->
    <div data-role="content">
        @RenderSection("featured", false)
        @RenderBody()
    </div>

</body>
</html>

ProjektPuszcze/Views/Shared/_ViewSwitcher.cshtml
@if (Request.Browser.IsMobileDevice && Request.HttpMethod == "GET")
{
    <div class="view-switcher ui-bar-a">
        @if (ViewContext.HttpContext.GetOverriddenBrowser().IsMobileDevice)
        {
            @: Displaying mobile view
            @Html.ActionLink("przełącz", "SwitchView", "ViewSwitcher", new { mobile = false, returnUrl = Request.Url.PathAndQuery }, new { rel = "external" })
        } 
        else 
        {
            @: Displaying desktop view
            @Html.ActionLink("przełącz", "SwitchView", "ViewSwitcher", new { mobile = true, returnUrl = Request.Url.PathAndQuery }, new { rel = "external" })
        }
    </div>
}